<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
    </button>
    <button type="button"
            title="<?= /* @escapeNotVerified */ __('Get Credit') ?>"
            onclick="setLocation('yes-money-credit')"
            class="action primary credit"
        <span><?= /* @escapeNotVerified */ __('Get Credit') ?></span>
    </button>
<?php endif?>
<script type="text/javascript">
    function setLocation(urlKey){
        var url = '<?= $block->getBaseUrl() ?>'+urlKey;
        window.open(url,'_blank');
    }
</script>


