<?php
/**
 * Copyright © Conn's. All rights reserved.
 * See LICENSE.txt for license details.
 */
$search = $block->request->getParam('search');
$distance = $block->request->getParam('distance');
?>
<form class="storelocator-filter" autocomplete="off" id="storelocator-filter" novalidate>
    <h4><?php echo __('Find Your Conn\'s HomePlus')?></h4>
    <div style="display: none">
        <label><input type="checkbox" name="advanced_search" id="advanced_search" value="1" autocomplete="off" /> Advanced Filter</label>
    </div>
    <hr />
    <fieldset class="fieldset" data-role="filter_group" id="simple-search-block">
        <div class="field address">
            <label class="label" for="address"><?php echo __('Enter Zip Code OR City, State and Select Search Radius ')?></label>
            <div class="control">
                <input type="text" name="address" id="address" class="input-text required-entry" value="<?= /*@escapedNotVerified*/ isset($search)?$search:"";?>" />
            </div>
        </div>

        <div class="field distance">
            <div class="control">
                <select  class="input-text" name="distance" id="distance">
                    <?php $distanceCollection = $block->getAvailableDistance()?>
                    <?php foreach ($distanceCollection as $item):?>
                        <option value="<?php echo $block->escapeHtml($item)?>"
                                <?php if ($item==$block->getDefaultDistance() && !isset($distance)):?>
                                    selected="selected"
                                <?php elseif(isset($distance)):?>
                                    selected="selected"
                                <?php endif;?>
                        >
                            <?php echo $block->escapeHtml($item)?> <?php echo $block->getUnit($item)?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
    </fieldset>
    <div class="filter-action">
        <hr />
        <button class="action primary" type="submit" data-role="search-location"><?php echo __('Find Store')?></button>
    </div>
</form>
