<?php
/**
 * Copyright © Conn's. All rights reserved.
 * See LICENSE.txt for license details.
 */
$zip = $block->request->getParam('zip_code');
$distance = $block->request->getParam('distance');
?>
<?php /** @var \Conns\PowerStore\Block\Search\Filter $block  */?>

<form class="storelocator-filter" autocomplete="off" id="storelocator-filter" novalidate>
    <h4><?php echo __('Enter Zip Code OR City, State and Select Search Radius')?></h4>
    <div style="display: none">
        <label><input type="checkbox" name="advanced_search" id="advanced_search" value="1" autocomplete="off" checked/> Advanced Filter</label>
    </div>
    <hr />
    <fieldset class="fieldset" data-role="filter_group" style="display: none" id="simple-search-block">
        <div class="field address">
            <label class="label" for="address"><?php echo __('Address')?></label>
            <div class="control">
                <input type="text" name="address" id="address" class="input-text required-entry" placeholder="<?php echo __('Please Enter City or State or Zip/Postal Code')?>"/>
            </div>
        </div>
        <div class="field distance">
            <label class="label" for="postcode"><?php echo __('Distance')?></label>
            <div class="control">
                <select  class="input-text" name="distance" id="distance" disabled>
                    <?php $distanceCollection = $block->getAvailableDistance()?>
                    <?php foreach ($distanceCollection as $item):?>
                        <option value="<?php echo $block->escapeHtml($item)?>"<?php if ($item==$block->getDefaultDistance()):?>selected="selected"<?php endif;?>><?php echo $block->escapeHtml($item)?> <?php echo $block->getUnit($item)?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset" data-role="filter_group" id="advanced-search-block">
        <div class="field country">
            <div class="control">
                <input class="input-text" name="country_id" id="country_id" data-role="filter_field" hidden/>
            </div>
        </div>
        <div class="field region">
            <div class="control">
                <input class="input-text disabled" name="region" id="region_id" data-role="filter_field" hidden>
            </div>
        </div>
        <div class="field postcode">
            <div class="control">
                <input type="text" name="postcode" id="postcode"  data-role="filter_field" class="input-text disabled" <?php if(isset($zip)):?>value="<?=/*@escapedNorVerified*/$zip?>"<?php endif;?>/>
            </div>
        </div>
        <div class="field distance">
            <div class="control">
                <select  class="input-text" name="distance" id="distance_advance"  data-role="filter_field" >
                    <?php $distanceCollection = $block->getAvailableDistance()?>
                    <?php foreach ($distanceCollection as $item):?>
                        <option
                                value="<?php echo $block->escapeHtml($item)?>"
                                <?php if ($item==$block->getDefaultDistance() && !isset($distance)):?>
                                    selected="selected"
                                <?php elseif ($item==$distance):?>
                                    selected="selected"
                                <?php endif;?>
                        >
                            <?php echo $block->escapeHtml($item)?> <?php echo $block->getUnit($item)?>
                        </option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <div class="filter-action">
            <button class="action primary" type="submit" data-role="search-location"><?php echo __('Search')?></button>
        </div>
    </fieldset>
</form>
<?php if(isset($zip)):?>
    <script type="text/javascript">
        require(['jquery'],function ($) {
            var zipcode = $('#postcode').val();
            if(zipcode.length !== 0){
                window.setTimeout(function () {
                    $('.action.primary').click();
                },1000)
            }
        })
    </script>
<?php endif;?>