<?php
$helper = $block->getCompareHelper();
?>
<div class="compare-button-container no-display" data-bind="scope: 'compareProducts'">
    <!-- ko if: compareProducts().count > 1 && compareProducts().count < 6-->
    <div>
        <a href="<?=$block->escapeHtml($helper->getListUrl())?>" class="action compare primary">
            <span><?php /* @escapeNotVerified */ echo __('Compare Now') ?></span>
        </a>
    </div>
    <!-- /ko -->
</div>
<input type="checkbox" class="comparestatus" />
<a
   class="connstocompare compare-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>"
   href="javascript:void(0)"
   title="<?php echo $block->escapeHtml(__('Compare')); ?>"
   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
   data-compare='<?php /* @escapeNotVerified */ echo $helper->getCompareData($block->getProduct()); ?>'
   role="button">
    <span><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
</a>
<style type="text/css">
    .connstocompare.active { visibility: hidden }
    .compare-button-container.no-display { visibility:hidden }
</style>