<?php
$helper = $block->getCompareHelper();
?>
<div class="compare-button-container no-display" data-bind="scope: 'compareProducts'">
    <div data-bind="click:function() { _compareProduct('<?=$block->escapeHtml($helper->getListUrl())?>'); }">
        <a href="javascript:void(0)" class="action compare primary"><span><?php /* @escapeNotVerified */ echo __('Compare Now') ?></span></a>
    </div>
</div>
<input type="checkbox" class="comparestatus" />
<a
   class="connstocompare compare-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>"
   href="javascript:void(0)"
   title="<?php echo $block->escapeHtml(__('Compare')); ?>"
   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
   data-compare='<?php /* @escapeNotVerified */ echo $helper->getCompareData($block->getProduct()); ?>'
   role="button">
    <span><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
</a>
<style type="text/css">
    .connstocompare.active { visibility: hidden }
    .compare-button-container.no-display { visibility:hidden }
</style>