<?php
   $_regions = $block->getAllRegions();
?>
<div class="col-left-sidebar-container">
    <div id="row-form">
        <form class="storelocator-filter" autocomplete="off" id="storelocator-filter" action="<?=/*@escapedNotVerified*/$block->getSearchPageUrl()?>" novalidate>
            <h4><?php echo __('Enter Zip Code OR City, State and Select Search Radius')?></h4>
            <fieldset class="fieldset" id="simple-search-block">
                <div class="field search-type">
                    <div class="control">
                        <input type="text" name="search_type" id="search_type" value="simple" hidden/>
                    </div>
                </div>
                <div class="field current-page">
                    <div class="control">
                        <input type="text" name="current_page" id="current_page" value="1" hidden/>
                    </div>
                </div>
                <div class="field page-size">
                    <div class="control">
                        <input type="text" name="page_size" id="page_size" value="10" hidden/>
                    </div>
                </div>
                <div class="page">
                    <div class="control">
                        <input type="text" name="page" id="page" value="1" hidden/>
                    </div>
                </div>
                <div class="field search">
                    <div class="control">
                        <input type="text" name="search" id="form-search" />
                    </div>
                </div>
                <div class="error-message" style="display: none"><strong><p style="color: red">Store not found. Please enter different Zip Code OR City, State.</p><strong></div>
                <div class="field distance-value">
                    <div class="control">
                        <select  class="input-text" name="distance" id="form-distance" >
                            <?php $distanceCollection = $block->getAvailableDistance()?>
                            <?php foreach ($distanceCollection as $item):?>
                                <option
                                        value="<?php echo $block->escapeHtml($item)?>"
                                    <?php if ($item==$block->getDefaultDistance()):?>
                                        selected="selected"
                                    <?php endif;?>
                                >
                                    <?php echo $block->escapeHtml($item)?> <?php echo $block->getUnit($item)?>
                                </option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="filter-action">
                    <input class="action primary submit" type="button" value="Find Store"/>
                </div>
                <button class="verify-submit" type="submit" style="visibility: hidden"></button>
            </fieldset>
        </form>
    </div>
    <div id="row-region-list">
        <h4><?= /*@escapedNotVerified*/__('Choose Your Region') ?></h4>
        <dl>
            <?php $rowCount = 1;?>
            <?php foreach($_regions as $regionName => $region): ?>
                <?php $item_id = 'menu_item_' . preg_replace('/[^a-zA-Z]/', '_', strtolower($regionName)); ?>
                <dt class="choose-region<?php echo $rowCount;?>">
                    <?php if (isset($region['id']) && $region['url_key'] !== 'allsites'): ?>
                        <a href="<?= /*@escapedNotVerified*/$block->getRegionPageUrl($region['url_key']) ?>" >
                            <span><?php echo $regionName ?></span>
                        </a>
                    <?php elseif(isset($region['id']) && $region['url_key'] == 'allsites'): ?>
                        <a href="<?= /*@escapedNotVerified*/$block->getAllRegionPageUrl() ?>" >
                            <span><?php echo $regionName ?></span>
                        </a>
                    <?php else: ?>
                        <span class="close"><?php echo $regionName ?></span>
                    <?php endif; ?>
                </dt>
                <?php if (isset($region['cities'])): ?>
                    <dd id="showCityForRegion">
                        <dl>
                            <?php foreach($region['cities'] as $cityName => $city): ?>
                                <dt>
                                    <a href="<?= /*@escapedNotVerified*/$block->getRegionPageUrl($city['url_key'])?>">
                                        <span><?php echo $cityName ?></span>
                                    </a>
                                </dt>
                            <?php endforeach ?>
                        </dl>
                    </dd>
                <?php endif ?><?php $rowCount++;
            endforeach; ?>
        </dl>
    </div>
</div>
<script type="text/javascript">
    require(['jquery','Magento_Ui/js/modal/alert'],function ($,alert) {
        $('.submit').on('click',function () {
            var postcode = $('#form-search').val();
            var distance = $('#form-distance').val();
            if(postcode == ''){
                alert({
                    content: "Please enter Zipcode, City or State",
                    actions: {}
                });
            }
            else {
                $.ajax({
                    showLoader: true,
                    url: "<?=/*@escapedNotVerified*/ $block->getCheckResultsUrl()?>",
                    data:{
                        'postcode': postcode,
                        'distance': distance
                    },
                    type: "GET",
                    dataType: 'json',
                    success: function (data,status,xhr) {
                        if(data.success == true){
                            $('.verify-submit').click();
                        }else{
                            $('.error-message').fadeIn(1000);
                            $('.error-message').fadeOut(4000);
                        }
                    },
                    error: function (jqXhr, textStatus, errorMessage) {
                        alert('Request Failed');
                    }
                });
            }
        });
        $(document).ready(function () {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var lat = position.coords.latitude;
                    var long = position.coords.longitude;
                    $.ajax({
                        showLoader: false,
                        url: "<?=/*@escapedNotVerified*/ $block->getZipRequestUrl()?>",
                        data:{
                            'lat': lat,
                            'long': long
                        },
                        type: "POST",
                        dataType: 'json',
                        success: function (data,status,xhr) {
                            if(data.success == true){
                                console.log(data.zip);
                                $('#form-search').val(data.zip);
                                $('.verify-submit').click();
                            }else{
                                alert({
                                    content: "Unable to find zip code",
                                    actions: {}
                                    });
                            }
                        },
                        error: function (jqXhr, textStatus, errorMessage) {
                            alert('Request Failed');
                        }
                    });
                });
            }
            else{
                alert({
                    content: "Unable to find zip code",
                    actions: {}
                });
            }
        });
    });
</script>